<?php 
// Autogenerated - Never Executed, but used to create translations of table entries 
include stageshowplus_main.php 

//---------- ADMIN\STAGESHOWPLUS_EXPORT.PHP

//---------- ADMIN\STAGESHOWPLUS_MANAGE_OVERVIEW.PHP

//---------- ADMIN\STAGESHOWPLUS_MANAGE_PERFORMANCES.PHP
$ourText = __('Expires', 'stageshow'); // Line: 59 
$ourText = __('Note Position', 'stageshow'); // Line: 60 
$ourText = __('Note', 'stageshow'); // Line: 61 

//---------- ADMIN\STAGESHOWPLUS_MANAGE_PRICEPLANS.PHP
$ourText = __('Ticket Type', 'stageshow'); // Line: 64 
$ourText = __('Price', 'stageshow'); // Line: 65 
$ourText = __('Visibility', 'stageshow'); // Line: 66 

//---------- ADMIN\STAGESHOWPLUS_MANAGE_PRICES.PHP
$ourText = __('Visibility', 'stageshow'); // Line: 43 

//---------- ADMIN\STAGESHOWPLUS_MANAGE_SALES.PHP
			/* return StageShowLibAdminClass::ActionButtonHTML */ $unusedVal = __('Edit Sale', $this->caller, $this->myDomain, 'edit-entry-button', $result->saleID);    

//---------- ADMIN\STAGESHOWPLUS_MANAGE_SETTINGS.PHP
$ourText = __('Reservations', 'stageshow'); // Line: 45 
$ourText = __('StageShow Sales EMail Name', 'stageshow'); // Line: 108 
$ourText = __('Reservation EMail Template', 'stageshow'); // Line: 110 
$ourText = __('Performance Expires Limit', 'stageshow'); // Line: 112 
$ourText = __('', 'stageshow'); // Line: 113 
$ourText = __('Terminal Location', 'stageshow'); // Line: 114 
$ourText = __('Sale Transaction ID', 'stageshow'); // Line: 116 
$ourText = __('Sale Txn EMail Address', 'stageshow'); // Line: 117 
$ourText = __('Sale Summary Report EMail', 'stageshow'); // Line: 119 
$ourText = __('Summary EMail Template', 'stageshow'); // Line: 120 
$ourText = __('Log Files Folder Path', 'stageshow'); // Line: 122 
$ourText = __('Reservations', 'stageshow'); // Line: 124 
$ourText = __('Address 1', 'stageshow'); // Line: 125 
$ourText = __('Address 2', 'stageshow'); // Line: 126 
$ourText = __('Address 3', 'stageshow'); // Line: 127 
$ourText = __('City', 'stageshow'); // Line: 128 
$ourText = __('County', 'stageshow'); // Line: 129 
$ourText = __('Postcode', 'stageshow'); // Line: 130 
$ourText = __('Country', 'stageshow'); // Line: 131 
$ourText = __('Phone', 'stageshow'); // Line: 132 
$ourText = __('Enable Reservations', 'stageshow'); // Line: 124 

//---------- ADMIN\STAGESHOWPLUS_MANAGE_SHOWS.PHP
$ourText = __('Note', 'stageshow'); // Line: 44 
$ourText = __('EMail Template', 'stageshow'); // Line: 45 

//---------- ADMIN\STAGESHOWPLUS_MANAGE_TOOLS.PHP

//---------- ADMIN\STAGESHOWPLUS_OFX_EXPORT.PHP

//---------- ADMIN\STAGESHOWPRO_MANAGE_OVERVIEW.PHP

//---------- ADMIN\STAGESHOWPRO_MANAGE_PERFORMANCES.PHP
$ourText = __('Seating', 'stageshow'); // Line: 52 

//---------- ADMIN\STAGESHOWPRO_MANAGE_PRICEPLANS.PHP

//---------- ADMIN\STAGESHOWPRO_MANAGE_PRICES.PHP
$ourText = __('Zone', 'stageshow'); // Line: 53 

//---------- ADMIN\STAGESHOWPRO_MANAGE_SALES.PHP
$ourText = __('Seat', 'stageshow'); // Line: 57 

//---------- ADMIN\STAGESHOWPRO_MANAGE_SETTINGS.PHP
$ourText = __('Allocated Seating', 'stageshow'); // Line: 43 
$ourText = __('Enable Allocated Seating', 'stageshow'); // Line: 43 

//---------- ADMIN\STAGESHOWPRO_MANAGE_SHOWS.PHP

//---------- ADMIN\STAGESHOWPRO_MANAGE_TOOLS.PHP

//---------- ADMIN\STAGESHOW_BOXOFFICE.PHP

//---------- ADMIN\STAGESHOW_DEBUG.PHP

//---------- ADMIN\STAGESHOW_EXPORT.PHP

//---------- ADMIN\STAGESHOW_MANAGE_OVERVIEW.PHP
$ourText = __('Show', 'stageshow'); // Line: 54 
$ourText = __('Performances', 'stageshow'); // Line: 55 
$ourText = __('Tickets Sold', 'stageshow'); // Line: 56 
$ourText = __('Sales Value', 'stageshow'); // Line: 57 
$ourText = __('Name', 'stageshow'); // Line: 64 
$ourText = __('Performance', 'stageshow'); // Line: 147 
$ourText = __('Tickets Sold', 'stageshow'); // Line: 148 
$ourText = __('Sales Value', 'stageshow'); // Line: 149 

//---------- ADMIN\STAGESHOW_MANAGE_PERFORMANCES.PHP
$ourText = __('Date & Time', 'stageshow'); // Line: 61 
$ourText = __('Reference', 'stageshow'); // Line: 62 
$ourText = __('Max Seats', 'stageshow'); // Line: 63 
$ourText = __('Tickets Sold', 'stageshow'); // Line: 64 
$ourText = __('State', 'stageshow'); // Line: 65 

//---------- ADMIN\STAGESHOW_MANAGE_PRICES.PHP
$ourText = __('Performance', 'stageshow'); // Line: 67 
$ourText = __('Ticket Type', 'stageshow'); // Line: 68 
$ourText = __('Price', 'stageshow'); // Line: 69 

//---------- ADMIN\STAGESHOW_MANAGE_SALES.PHP

//---------- ADMIN\STAGESHOW_MANAGE_SETTINGS.PHP
$ourText = __('General', 'stageshow'); // Line: 53 
$ourText = __('Advanced', 'stageshow'); // Line: 54 
$ourText = __('Organisation ID', 'stageshow'); // Line: 75 
$ourText = __('Sale EMail Template', 'stageshow'); // Line: 76 
$ourText = __('StageShow Sales EMail', 'stageshow'); // Line: 77 
$ourText = __('Bcc EMails to WP Admin', 'stageshow'); // Line: 78 
$ourText = __('Currency Symbol', 'stageshow'); // Line: 79 
$ourText = __('Items per Page', 'stageshow'); // Line: 80 
$ourText = __('Max Ticket Qty', 'stageshow'); // Line: 81 
$ourText = __('Checkout Note Position', 'stageshow'); // Line: 83 
$ourText = __('Checkout Note', 'stageshow'); // Line: 84 
$ourText = __('Send EMail confirmation to Administrator', 'stageshow'); // Line: 78 
$ourText = __('Include in Box Office Output', 'stageshow'); // Line: 79 

//---------- ADMIN\STAGESHOW_MANAGE_SHOWS.PHP
$ourText = __('Show Name', 'stageshow'); // Line: 58 
$ourText = __('Tickets Sold', 'stageshow'); // Line: 59 
$ourText = __('State', 'stageshow'); // Line: 60 

//---------- ADMIN\STAGESHOW_MANAGE_TOOLS.PHP

//---------- ADMIN\STAGESHOW_TDT_EXPORT.PHP

//---------- INCLUDE\STAGESHOWLIB_ADMIN.PHP

//---------- INCLUDE\STAGESHOWLIB_DBASE_API.PHP

//---------- INCLUDE\STAGESHOWLIB_DEBUG.PHP

//---------- INCLUDE\STAGESHOWLIB_EMAIL_API.PHP

//---------- INCLUDE\STAGESHOWLIB_EXPORT.PHP

//---------- INCLUDE\STAGESHOWLIB_HTMLEMAIL_API.PHP

//---------- INCLUDE\STAGESHOWLIB_IPN_CALLBACK.PHP

//---------- INCLUDE\STAGESHOWLIB_LOGFILE.PHP

//---------- INCLUDE\STAGESHOWLIB_PAYPAL_API.PHP

//---------- INCLUDE\STAGESHOWLIB_PAYPAL_SALESADMIN.PHP
					/* return StageShowLibAdminClass::ActionButtonHTML */ $unusedVal = __('Back to Sales Summary', $this->caller, $this->myDomain, 'tablenav_bottom_actions'); 
					/* return StageShowLibAdminClass::ActionButtonHTML */ $unusedVal = __('Send Confirmation EMail', $this->caller, $this->myDomain, 'tablenav_bottom_actions'); 
$ourText = __('Name', 'stageshow'); // Line: 83 
$ourText = __('Transaction Date', 'stageshow'); // Line: 84 
$ourText = __('Status', 'stageshow'); // Line: 85 
$ourText = __('First Name', 'stageshow'); // Line: 109 
$ourText = __('Last Name', 'stageshow'); // Line: 110 
$ourText = __('EMail', 'stageshow'); // Line: 111 
$ourText = __('Total Paid/Due', 'stageshow'); // Line: 118 
$ourText = __('Fee', 'stageshow'); // Line: 119 
$ourText = __('Transaction Date & Time', 'stageshow'); // Line: 120 
$ourText = __('Transaction ID', 'stageshow'); // Line: 121 
$ourText = __('Status', 'stageshow'); // Line: 122 

//---------- INCLUDE\STAGESHOWLIB_PAYPAL_SETTINGS.PHP
$ourText = __('PayPal', 'stageshow'); // Line: 60 
$ourText = __('Environment', 'stageshow'); // Line: 81 
$ourText = __('Merchant ID', 'stageshow'); // Line: 82 
$ourText = __('API User', 'stageshow'); // Line: 83 
$ourText = __('API Password', 'stageshow'); // Line: 84 
$ourText = __('API Signature', 'stageshow'); // Line: 85 
$ourText = __('Account EMail', 'stageshow'); // Line: 86 
$ourText = __('Checkout Timeout', 'stageshow'); // Line: 87 
$ourText = __('Currency', 'stageshow'); // Line: 88 
$ourText = __('PayPal Header Image File', 'stageshow'); // Line: 89 
$ourText = __('EMail Logo Image File', 'stageshow'); // Line: 90 
$ourText = __('Checkout Complete URL', 'stageshow'); // Line: 91 
$ourText = __('Checkout Cancelled URL', 'stageshow'); // Line: 92 

//---------- INCLUDE\STAGESHOWLIB_SALESPLUGIN.PHP

//---------- INCLUDE\STAGESHOWLIB_SALES_DBASE_API.PHP

//---------- INCLUDE\STAGESHOWLIB_SALES_OFX.PHP

//---------- INCLUDE\STAGESHOWLIB_TABLE.PHP

//---------- INCLUDE\STAGESHOWLIB_TEST_EMAILSALE.PHP

//---------- INCLUDE\STAGESHOWLIB_UTILS.PHP

//---------- INCLUDE\STAGESHOWPLUS_BARCODE.PHP

//---------- INCLUDE\STAGESHOWPLUS_DBASE_API.PHP

//---------- INCLUDE\STAGESHOWPLUS_EMAIL_API.PHP

//---------- INCLUDE\STAGESHOWPRO_DBASE_API.PHP

//---------- INCLUDE\STAGESHOW_DBASE_API.PHP

//---------- INCLUDE\STAGESHOW_SALES_TABLE.PHP
$ourText = __('Sale Editor', 'stageshow'); // Line: 41 
$ourText = __('Paid/Due', 'stageshow'); // Line: 45 
$ourText = __('Quantity', 'stageshow'); // Line: 46 
$ourText = __('Show', 'stageshow'); // Line: 99 
$ourText = __('Performance', 'stageshow'); // Line: 100 
$ourText = __('Ticket Type', 'stageshow'); // Line: 101 
$ourText = __('Price', 'stageshow'); // Line: 102 
$ourText = __('Quantity', 'stageshow'); // Line: 103 
?> 
